export default {
    darkMode: "class",
    content: ["./**/*.{ts,tsx,js,jsx,html}"],
    theme: {
        extend: {
            colors: {
                canvas: "var(--canvas)",
                surface: "var(--surface)",
                "surface-2": "var(--surface-2)",
                line: "var(--line)",
                "line-soft": "var(--line-soft)",
                "line-strong": "var(--line-strong)",
                ink: "var(--ink)",
                "ink-2": "var(--ink-2)",
                "ink-3": "var(--ink-3)",
                navy: "var(--navy)",
                "navy-soft": "var(--navy-soft)",
                "navy-tint": "var(--navy-tint)",
                "on-navy": "var(--on-navy)",
                accent: "var(--accent)",
                safe: "var(--safe)",
                "safe-vivid": "var(--safe-vivid)",
                "safe-tint": "var(--safe-tint)",
                caution: "var(--caution)",
                "caution-vivid": "var(--caution-vivid)",
                "caution-tint": "var(--caution-tint)",
                danger: "var(--danger)",
                "danger-vivid": "var(--danger-vivid)",
                "danger-tint": "var(--danger-tint)",
                "map-base": "var(--map-base)",
                "map-road": "var(--map-road)",
            },
            backgroundImage: {
                "grad-navy": "var(--grad-navy)",
                "grad-navy-soft": "var(--grad-navy-soft)",
                "grad-navy-pill": "var(--grad-navy-pill)",
                "grad-surface": "var(--grad-surface)",
                "grad-canvas": "var(--grad-canvas)",
                "grad-header": "var(--grad-header)",
                "grad-sheen": "var(--grad-sheen)",
                "grad-safe": "var(--grad-safe)",
                "grad-caution": "var(--grad-caution)",
                "grad-danger": "var(--grad-danger)",
                "grad-scrim-top": "var(--grad-scrim-top)",
                "grad-scrim-bottom": "var(--grad-scrim-bottom)",
            },
            fontFamily: {
                sans: [
                    "Pretendard Variable",
                    "Pretendard",
                    "-apple-system",
                    "BlinkMacSystemFont",
                    "Apple SD Gothic Neo",
                    "system-ui",
                    "sans-serif",
                ],
            },
            borderRadius: {
                btn: "14px",
                card: "20px",
                modal: "24px",
            },
            boxShadow: {
                card: "var(--shadow-card)",
                float: "var(--shadow-float)",
                lifted: "var(--shadow-lifted)",
                modal: "var(--shadow-modal)",
                tabbar: "var(--shadow-tabbar)",
                navy: "var(--shadow-navy)",
                "navy-pressed": "var(--shadow-navy-pressed)",
                inset: "var(--shadow-inset)",
                "card-inset": "var(--shadow-card), var(--shadow-inset)",
                "float-inset": "var(--shadow-float), var(--shadow-inset)",
                "lifted-inset": "var(--shadow-lifted), var(--shadow-inset)",
                "navy-inset": "var(--shadow-navy), var(--shadow-inset-navy)",
                "navy-pressed-inset": "var(--shadow-navy-pressed), var(--shadow-inset-navy)",
            },
            transitionTimingFunction: {
                smooth: "cubic-bezier(0.23, 1, 0.32, 1)",
            },
        },
    },
    plugins: [],
}
